const ML_MODEL_VARIABLES = [
    {
        key: "immovables",
        options: ["0", "1-2", ">2"]
    },
    {
        key: "monthly_income",
        options: ["<500", "<1000", ">1000"]
    },
    {
        key: "employment_situation",
        options: ["employee", "self-employed", "unemployed"]
    },
    {
        key: "has_tesla",
        options: ["no", "yes"]
    }
];

const BIOMETRIC_VALIDATION_VERIFIED = 'VERIFIED';
const BIOMETRIC_VALIDATION_PENDING = 'PENDING';
const BIOMETRIC_VALIDATION_INVALID = 'INVALID';
const CREDIT_SCORE_VALIDATION_FRAUD = 'FRAUD';
const CREDIT_SCORE_VALIDATION_PENDING_RISKY = 'PENDING_RISKY';
const CREDIT_SCORE_VALIDATION_PENDING_RELIABLE = 'PENDING_RELIABLE';
const CREDIT_SCORE_VALIDATION_TRUSTWORTHY = 'TRUSTWORTHY';
const APPROVED_STATUS_APPROVED = 'APPROVED';
const APPROVED_STATUS_REJECTED = 'REJECTED';
const APPROVED_STATUS_PENDING = 'PENDING';

const BIOMETRIC_VALIDATION = [
    BIOMETRIC_VALIDATION_VERIFIED,
    BIOMETRIC_VALIDATION_PENDING,
    BIOMETRIC_VALIDATION_INVALID
];

const CREDIT_SCORE_VALIDATION = [
    CREDIT_SCORE_VALIDATION_FRAUD, 
    CREDIT_SCORE_VALIDATION_PENDING_RISKY, 
    CREDIT_SCORE_VALIDATION_PENDING_RELIABLE, 
    CREDIT_SCORE_VALIDATION_TRUSTWORTHY
];

const APPROVED_STATUS = [
    APPROVED_STATUS_APPROVED,
    APPROVED_STATUS_REJECTED,
    APPROVED_STATUS_PENDING
];

module.exports = { 
    ML_MODEL_VARIABLES,  
    BIOMETRIC_VALIDATION, 
    CREDIT_SCORE_VALIDATION,
    CREDIT_SCORE_VALIDATION_FRAUD,
    BIOMETRIC_VALIDATION_PENDING,
    BIOMETRIC_VALIDATION_INVALID,
    APPROVED_STATUS,
    APPROVED_STATUS_PENDING
};